### ISSUE TITLE
Failed to install RPE

### ISSUE THREAD

**Issue by omniokami** [furudean/vscode-renpy-warp#50]
After enabling **Renpy Extensions Enabled** setting (for cursor follow feature) I have an Error.
Could it be related to [Renpy Language](https://marketplace.visualstudio.com/items?itemName=LuqueDaniel.languague-renpy
) extension deprecation? I had to switch to [Ren'Py Language (8.3+)](https://marketplace.visualstudio.com/items?itemName=renpy.language-renpy) one.
![image](https://github.com/user-attachments/assets/55c35672-aa72-4016-9be0-21442b7fd4a5)
![image](https://github.com/user-attachments/assets/b9361dd9-29c5-4085-bf19-e1ab29e766c4)

Thank you in advance!

**Comment by furudean** [comment]
Fixed in https://github.com/furudean/vscode-renpy-warp/releases/tag/v1.19.1, thanks for reporting!

**Comment by omniokami** [comment]
Wow, that was quick, great job! Thank you
